//
// Created by plaka on 03.02.2023.
//

#ifndef LIVERUSSIA_CGTAWIDGETS_H
#define LIVERUSSIA_CGTAWIDGETS_H


#include <cstdint>

class CGtaWidgets {


public:
    static uintptr_t* pWidgets;

    static void setEnabled(int thiz, bool bEnabled);

    static void init();
};

enum
{
    WIDGET_POSITION_ENTER_CAR,
    WIDGET_POSITION_CAR_SHOOT,
    WIDGET_POSITION_ACCELERATE,
    WIDGET_POSITION_BUTTON_SPRINT_AND_SWIM,
    WIDGET_POSITION_BRAKE,
    WIDGET_POSITION_VEHICLE_STEER_LEFT,
    WIDGET_POSITION_VEHICLE_STEER_RIGHT,
    WIDGET_POSITION_HORN,
    WIDGET_POSITION_HORN_ALT,
    WIDGET_POSITION_PHONE,
    WIDGET_POSITION_VEHICLE_SHOOT_LEFT,
    WIDGET_POSITION_VEHICLE_SHOOT_RIGHT,
    WIDGET_POSITION_HANDBRAKE_AND_AIR_SHOOT,
    WIDGET_POSITION_CAM_TOGGLE,
    WIDGET_POSITION_TARGETING_AND_ATTACK,
    WIDGET_POSITION_VC_SHOOT,
    WIDGET_POSITION_VC_SHOOT_ALT,
    WIDGET_POSITION_SWAP_WEAPONS,
    WIDGET_POSITION_PLACE_BET,
    WIDGET_POSITION_REMOVE_BET,
    WIDGET_POSITION_NEGATIVE,
    WIDGET_POSITION_POSITIVE,
    WIDGET_POSITION_POOL_ENGLISH
};

#endif //LIVERUSSIA_CGTAWIDGETS_H
