//
// Created by plaka on 17.03.2023.
//

#ifndef LIVERUSSIA_STREAMINGINFO_H
#define LIVERUSSIA_STREAMINGINFO_H

enum eStreamingFlags {
    STREAMING_DEFAULT = 0x0,
    STREAMING_UNKNOWN_1 = 0x1,
    STREAMING_GAME_REQUIRED = 0x2,
    STREAMING_MISSION_REQUIRED = 0x4,
    STREAMING_KEEP_IN_MEMORY = 0x8,
    STREAMING_PRIORITY_REQUEST = 0x10,
    STREAMING_LOADING_SCENE = 0x20,
    STREAMING_DONTREMOVE_IN_LOADSCENE = STREAMING_LOADING_SCENE | STREAMING_PRIORITY_REQUEST | STREAMING_KEEP_IN_MEMORY | STREAMING_MISSION_REQUIRED | STREAMING_GAME_REQUIRED,
};

class StreamingInfo {

};


#endif //LIVERUSSIA_STREAMINGINFO_H
