/*
    Plugin-SDK (Grand Theft Auto San Andreas) header file
    Authors: GTA Community. See more here
    https://github.com/DK22Pac/plugin-sdk
    Do not delete this comment block. Respect others' work!
*/
#pragma once

enum eWeaponType : int
{
	GTASA_WEAPON_UNARMED = 0x0,
	GTASA_WEAPON_BRASSKNUCKLE = 0x1,
	GTASA_WEAPON_GOLFCLUB = 0x2,
	GTASA_WEAPON_NIGHTSTICK = 0x3,
	GTASA_WEAPON_KNIFE = 0x4,
	GTASA_WEAPON_BASEBALLBAT = 0x5,
	GTASA_WEAPON_SHOVEL = 0x6,
	GTASA_WEAPON_POOLCUE = 0x7,
	GTASA_WEAPON_KATANA = 0x8,
	GTASA_WEAPON_CHAINSAW = 0x9,
	GTASA_WEAPON_DILDO1 = 0xA,
	GTASA_WEAPON_DILDO2 = 0xB,
	GTASA_WEAPON_VIBE1 = 0xC,
	GTASA_WEAPON_VIBE2 = 0xD,
	GTASA_WEAPON_FLOWERS = 0xE,
	GTASA_WEAPON_CANE = 0xF,
	GTASA_WEAPON_GRENADE = 0x10,
	GTASA_WEAPON_TEARGAS = 0x11,
	GTASA_WEAPON_MOLOTOV = 0x12,
	GTASA_WEAPON_ROCKET = 0x13,
	GTASA_WEAPON_ROCKET_HS = 0x14,
	GTASA_WEAPON_FREEFALL_BOMB = 0x15,
	GTASA_WEAPON_PISTOL = 0x16,
	GTASA_WEAPON_PISTOL_SILENCED = 0x17,
	GTASA_WEAPON_DESERT_EAGLE = 0x18,
	GTASA_WEAPON_SHOTGUN = 0x19,
	GTASA_WEAPON_SAWNOFF = 0x1A,
	GTASA_WEAPON_SPAS12 = 0x1B,
	GTASA_WEAPON_MICRO_UZI = 0x1C,
	GTASA_WEAPON_MP5 = 0x1D,
	GTASA_WEAPON_AK47 = 0x1E,
	GTASA_WEAPON_M4 = 0x1F,
	GTASA_WEAPON_TEC9 = 0x20,
	GTASA_WEAPON_COUNTRYRIFLE = 0x21,
	GTASA_WEAPON_SNIPERRIFLE = 0x22,
	GTASA_WEAPON_RLAUNCHER = 0x23,
	GTASA_WEAPON_RLAUNCHER_HS = 0x24,
	GTASA_WEAPON_FTHROWER = 0x25,
	GTASA_WEAPON_MINIGUN = 0x26,
	GTASA_WEAPON_SATCHEL_CHARGE = 0x27,
	GTASA_WEAPON_DETONATOR = 0x28,
	GTASA_WEAPON_SPRAYCAN = 0x29,
	GTASA_WEAPON_EXTINGUISHER = 0x2A,
	GTASA_WEAPON_CAMERA = 0x2B,
	GTASA_WEAPON_NIGHTVISION = 0x2C,
	GTASA_WEAPON_INFRARED = 0x2D,
	GTASA_WEAPON_PARACHUTE = 0x2E,
	GTASA_WEAPON_UNUSED = 0x2F,
	GTASA_WEAPON_ARMOUR = 0x30,
	GTASA_WEAPON_FLARE = 0x3A
};