//
// Created by plaka on 05.04.2023.
//

#ifndef LIVERUSSIA_ANIMBLENDCALLBACKTYPE_H
#define LIVERUSSIA_ANIMBLENDCALLBACKTYPE_H


enum eAnimBlendCallbackType : uint32_t {
    ANIM_BLEND_CALLBACK_NONE = 0,
    ANIM_BLEND_CALLBACK_FINISH = 1,
    ANIM_BLEND_CALLBACK_DELETE = 2
};



#endif //LIVERUSSIA_ANIMBLENDCALLBACKTYPE_H
