//
// Created by plaka on 05.04.2023.
//

#ifndef LIVERUSSIA_PEDTYPE_H
#define LIVERUSSIA_PEDTYPE_H

enum ePedType : __int32
{
    PEDTYPE_PLAYER1 = 0x0,
    PEDTYPE_PLAYER2 = 0x1,
    PEDTYPE_PLAYER_NETWORK = 0x2,
    PEDTYPE_PLAYER_UNUSED = 0x3,
    PEDTYPE_CIVMALE = 0x4,
    PEDTYPE_CIVFEMALE = 0x5,
    PEDTYPE_COP = 0x6,
    PEDTYPE_GANG1 = 0x7,
    PEDTYPE_GANG2 = 0x8,
    PEDTYPE_GANG3 = 0x9,
    PEDTYPE_GANG4 = 0xA,
    PEDTYPE_GANG5 = 0xB,
    PEDTYPE_GANG6 = 0xC,
    PEDTYPE_GANG7 = 0xD,
    PEDTYPE_GANG8 = 0xE,
    PEDTYPE_GANG9 = 0xF,
    PEDTYPE_GANG10 = 0x10,
    PEDTYPE_DEALER = 0x11,
    PEDTYPE_MEDIC = 0x12,
    PEDTYPE_FIRE = 0x13,
    PEDTYPE_CRIMINAL = 0x14,
    PEDTYPE_BUM = 0x15,
    PEDTYPE_PROSTITUTE = 0x16,
    PEDTYPE_SPECIAL = 0x17,
    PEDTYPE_MISSION1 = 0x18,
    PEDTYPE_MISSION2 = 0x19,
    PEDTYPE_MISSION3 = 0x1A,
    PEDTYPE_MISSION4 = 0x1B,
    PEDTYPE_MISSION5 = 0x1C,
    PEDTYPE_MISSION6 = 0x1D,
    PEDTYPE_MISSION7 = 0x1E,
    PEDTYPE_MISSION8 = 0x1F,
    PEDTYPE_LAST_PEDTYPE = 0x20,
};


#endif //LIVERUSSIA_PEDTYPE_H
