//
// Created by plaka on 21.02.2023.
//

#ifndef LIVERUSSIA_VEHICLECLASS_H
#define LIVERUSSIA_VEHICLECLASS_H

enum eVehicleClass : int8_t {
    VEHICLE_CLASS_IGNORE = -1,
    VEHICLE_CLASS_NORMAL = 0,
    VEHICLE_CLASS_POORFAMILY,
    VEHICLE_CLASS_RICHFAMILY,
    VEHICLE_CLASS_EXECUTIVE,
    VEHICLE_CLASS_WORKER,
    VEHICLE_CLASS_BIG,
    VEHICLE_CLASS_TAXI,
    VEHICLE_CLASS_MOPED,
    VEHICLE_CLASS_MOTORBIKE,
    VEHICLE_CLASS_LEISUREBOAT,
    VEHICLE_CLASS_WORKERBOAT,
    VEHICLE_CLASS_BICYCLE,
};

#endif //LIVERUSSIA_VEHICLECLASS_H
